import { Company, JobPosting } from "./types";
import crawledJobsData from "./crawled-jobs.json";

export const companies: Company[] = [
  {
    id: "greenfield",
    name: "그린필드",
    initial: "그",
    colorClass: "bg-primary-500",
    industry: "핀테크",
    location: "서울 강남구",
    fundingStage: "시리즈 B",
    fundingAmount: "220억 원",
    orgStage: "스케일업",
    employeeCount: "180명",
    designBlogUrl: "https://design.greenfield.example.com",
    brunchUrl: "https://brunch.co.kr/@greenfield-design",
    description:
      "개인 자산관리 서비스를 만드는 핀테크 스타트업. 디자인 시스템 고도화에 투자하며 리서치 기반 의사결정을 중시합니다.",
    cultureTags: ["디자인 시스템", "리서치 중심", "주 4.5일제"],
  },
  {
    id: "moonlit",
    name: "문릿랩스",
    initial: "문",
    colorClass: "bg-primary-600",
    industry: "커머스",
    location: "서울 성동구",
    fundingStage: "시리즈 A",
    fundingAmount: "80억 원",
    orgStage: "스타트업",
    employeeCount: "45명",
    designBlogUrl: "https://moonlitlabs.example.com/blog",
    description:
      "버티컬 커머스 플랫폼. 소규모 크로스펑셔널 팀에서 PM, 개발, 디자인이 밀접하게 협업합니다.",
    cultureTags: ["애자일", "빠른 실험", "수평 조직"],
  },
  {
    id: "hanbit",
    name: "한빛테크놀로지",
    initial: "한",
    colorClass: "bg-neutral-700",
    industry: "대기업 SI/플랫폼",
    location: "경기 성남시",
    fundingStage: "상장",
    fundingAmount: "비공개",
    orgStage: "대기업",
    employeeCount: "3,200명",
    designBlogUrl: "https://tech.hanbit.example.com/design",
    description:
      "국내 대표 IT 대기업 계열사. 체계적인 프로세스와 대규모 서비스 운영 경험을 쌓을 수 있습니다.",
    cultureTags: ["체계적 프로세스", "대규모 서비스", "안정적 조직"],
  },
  {
    id: "rocketpaper",
    name: "로켓페이퍼",
    initial: "로",
    colorClass: "bg-primary-400",
    industry: "협업 툴 SaaS",
    location: "서울 마포구",
    fundingStage: "시드",
    fundingAmount: "12억 원",
    orgStage: "스타트업",
    employeeCount: "14명",
    brunchUrl: "https://brunch.co.kr/@rocketpaper",
    description:
      "B2B 협업 툴을 만드는 초기 스타트업. 디자이너가 프로덕트 방향을 함께 결정하는 문화를 지향합니다.",
    cultureTags: ["초기 멤버", "높은 자율성", "풀스택 디자인"],
  },
  {
    id: "atelierblue",
    name: "아틀리에블루",
    initial: "아",
    colorClass: "bg-primary-700",
    industry: "헬스케어",
    location: "서울 서초구",
    fundingStage: "시리즈 C",
    fundingAmount: "410억 원",
    orgStage: "스케일업",
    employeeCount: "260명",
    designBlogUrl: "https://atelierblue.example.com/design-blog",
    brunchUrl: "https://brunch.co.kr/@atelierblue",
    description:
      "디지털 헬스케어 서비스. 접근성과 신뢰도를 중요하게 여기는 디자인 조직 문화를 갖고 있습니다.",
    cultureTags: ["접근성", "데이터 기반", "디자인 QA 전담"],
  },
  {
    id: "kakao",
    name: "카카오",
    initial: "카",
    colorClass: "bg-yellow-500",
    industry: "IT 플랫폼",
    location: "경기 성남시 판교",
    fundingStage: "상장",
    fundingAmount: "비공개",
    orgStage: "대기업",
    employeeCount: "4,000명 이상",
    designBlogUrl: "https://brunch.co.kr/@kakao-it",
    description:
      "카카오톡을 비롯한 국내 대표 플랫폼 서비스를 운영하는 IT 기업. 자동으로 수집된 공식 채용페이지 공고입니다.",
    cultureTags: ["대규모 서비스", "디자인 시스템", "완전선택근무제"],
  },
  {
    id: "naver",
    name: "네이버",
    initial: "네",
    colorClass: "bg-green-600",
    industry: "IT 플랫폼",
    location: "경기 성남시 분당구",
    fundingStage: "상장",
    fundingAmount: "비공개",
    orgStage: "대기업",
    employeeCount: "4,000명 이상",
    description:
      "검색, 커머스, 콘텐츠 등 다양한 서비스를 운영하는 국내 최대 인터넷 기업. 자동으로 수집된 공식 채용페이지 공고입니다.",
    cultureTags: ["대규모 서비스", "다양한 서비스 포트폴리오"],
  },
  {
    id: "toss",
    name: "토스",
    initial: "토",
    colorClass: "bg-blue-500",
    industry: "핀테크",
    location: "서울 강남구",
    fundingStage: "상장",
    fundingAmount: "비공개",
    orgStage: "스케일업",
    employeeCount: "2,000명 이상",
    description:
      "간편송금으로 시작해 금융 전반으로 확장한 핀테크 기업. 자동으로 수집된 공식 채용페이지 공고입니다.",
    cultureTags: ["프로덕트 오너십", "빠른 실행력"],
  },
];

export const jobPostings: JobPosting[] = [
  {
    id: "job-01",
    title: "Product Designer (UX/UI) - 자산관리 서비스",
    companyId: "greenfield",
    platform: "LinkedIn",
    location: "서울 강남구",
    career: "경력 3~5년",
    employmentType: "정규직",
    postedAt: "2026-06-28",
    deadline: "2026-07-20",
    tags: ["Figma", "디자인시스템", "핀테크"],
    jdSummary:
      "자산관리 앱의 핵심 플로우를 담당할 프로덕트 디자이너를 찾습니다. 디자인 시스템 운영 경험 우대.",
    jdFull: [
      "그린필드는 개인 자산관리 서비스를 만드는 핀테크 스타트업입니다.",
      "[주요 업무]",
      "- 자산관리 앱의 핵심 사용자 플로우 UX/UI 설계",
      "- 사내 디자인 시스템(Greenfield DS) 운영 및 컴포넌트 개선",
      "- 정성/정량 리서치를 바탕으로 한 가설 검증 및 개선",
      "- PM, 개발자와의 밀접한 협업을 통한 스프린트 단위 프로덕트 개발",
      "[자격 요건]",
      "- UX/UI 디자인 경력 3년 이상",
      "- Figma를 활용한 컴포넌트 기반 설계 경험",
      "- 사용자 리서치 및 데이터 기반 의사결정 경험",
      "[우대 사항]",
      "- 금융/핀테크 서비스 디자인 경험",
      "- 디자인 시스템 구축 및 운영 경험",
      "- 접근성(A11y) 가이드라인 이해",
    ],
    originalUrl: "https://www.linkedin.com/jobs/view/job-01",
    aiAnalysis: {
      coreSkills: [
        "사용자 플로우 설계",
        "디자인 시스템 운영",
        "정성/정량 리서치 해석",
        "크로스펑셔널 협업",
      ],
      requiredTools: ["Figma", "FigJam"],
      preferred: ["핀테크 도메인 경험", "디자인 시스템 구축 경험", "웹 접근성(A11y)"],
      keywords: [
        { keyword: "디자인 시스템", count: 5 },
        { keyword: "리서치", count: 4 },
        { keyword: "Figma", count: 3 },
        { keyword: "협업", count: 3 },
        { keyword: "핀테크", count: 2 },
      ],
    },
  },
  {
    id: "job-02",
    title: "UI 디자이너 (커머스 앱)",
    companyId: "moonlit",
    platform: "원티드",
    location: "서울 성동구",
    career: "경력 1~3년",
    employmentType: "정규직",
    postedAt: "2026-06-30",
    deadline: "2026-07-15",
    tags: ["Figma", "커머스", "모바일"],
    jdSummary:
      "버티컬 커머스 앱의 UI 디자인을 담당할 디자이너를 모집합니다. 빠른 실험과 반복이 익숙한 분을 찾습니다.",
    jdFull: [
      "문릿랩스는 버티컬 커머스 플랫폼을 운영하는 스타트업입니다.",
      "[주요 업무]",
      "- 커머스 앱 UI 디자인 및 프로토타이핑",
      "- A/B 테스트를 통한 전환율 개선 실험",
      "- 마케팅/CRM 캠페인용 비주얼 가이드 제작",
      "[자격 요건]",
      "- UI 디자인 경력 1년 이상",
      "- Figma, Sketch 등 디자인 툴 능숙",
      "- 빠른 실행력과 커뮤니케이션 능력",
      "[우대 사항]",
      "- 커머스/리테일 서비스 경험",
      "- 애니메이션 및 마이크로 인터랙션 설계 경험",
    ],
    originalUrl: "https://www.wanted.co.kr/wd/job-02",
    aiAnalysis: {
      coreSkills: ["UI 프로토타이핑", "A/B 테스트 설계", "비주얼 가이드 제작"],
      requiredTools: ["Figma", "Sketch"],
      preferred: ["커머스 도메인 경험", "마이크로 인터랙션 설계"],
      keywords: [
        { keyword: "커머스", count: 4 },
        { keyword: "Figma", count: 3 },
        { keyword: "실험", count: 3 },
        { keyword: "전환율", count: 2 },
      ],
    },
  },
  {
    id: "job-03",
    title: "시니어 UX 디자이너",
    companyId: "hanbit",
    platform: "잡코리아",
    location: "경기 성남시",
    career: "경력 5년 이상",
    employmentType: "정규직",
    postedAt: "2026-06-20",
    deadline: "2026-07-31",
    tags: ["대규모 서비스", "UX 리서치", "Sketch"],
    jdSummary:
      "대규모 트래픽 서비스의 UX 전략을 수립할 시니어 디자이너를 찾습니다.",
    jdFull: [
      "한빛테크놀로지는 국내 대표 IT 대기업 계열사입니다.",
      "[주요 업무]",
      "- 대규모 서비스의 UX 전략 수립 및 로드맵 관리",
      "- 주니어 디자이너 멘토링 및 프로세스 관리",
      "- 유관 부서와의 협의를 통한 서비스 정책 반영",
      "[자격 요건]",
      "- UX 디자인 경력 5년 이상",
      "- 대규모 서비스 운영 경험",
      "- Sketch, Figma, Zeplin 활용 가능",
      "[우대 사항]",
      "- 팀 리딩 또는 멘토링 경험",
      "- 접근성 표준 준수 경험",
    ],
    originalUrl: "https://www.jobkorea.co.kr/Recruit/GI_Read/job-03",
    aiAnalysis: {
      coreSkills: ["UX 전략 수립", "멘토링", "이해관계자 협의"],
      requiredTools: ["Sketch", "Figma", "Zeplin"],
      preferred: ["팀 리딩 경험", "접근성 표준"],
      keywords: [
        { keyword: "UX 전략", count: 3 },
        { keyword: "대규모 서비스", count: 3 },
        { keyword: "멘토링", count: 2 },
        { keyword: "프로세스", count: 2 },
      ],
    },
  },
  {
    id: "job-04",
    title: "프로덕트 디자이너 (초기 멤버)",
    companyId: "rocketpaper",
    platform: "로켓펀치",
    location: "서울 마포구 (리모트 가능)",
    career: "경력무관",
    employmentType: "정규직",
    postedAt: "2026-07-01",
    deadline: null,
    tags: ["B2B SaaS", "초기멤버", "리모트"],
    jdSummary:
      "B2B 협업 툴을 함께 만들어갈 초기 멤버 디자이너를 상시 모집합니다.",
    jdFull: [
      "로켓페이퍼는 B2B 협업 툴을 만드는 초기 스타트업입니다.",
      "[주요 업무]",
      "- 프로덕트 전반의 UX/UI 설계",
      "- 브랜딩, 마케팅 페이지 등 디자인 전반 담당",
      "- 창업 멤버들과 함께 프로덕트 방향 논의",
      "[자격 요건]",
      "- Figma를 활용한 UX/UI 설계 경험",
      "- 0에서 1을 만드는 과정에 대한 관심",
      "[우대 사항]",
      "- B2B SaaS 서비스 디자인 경험",
      "- 프론트엔드 코드 이해(HTML/CSS)",
    ],
    originalUrl: "https://www.rocketpunch.com/jobs/job-04",
    aiAnalysis: {
      coreSkills: ["0-to-1 프로덕트 설계", "브랜딩", "빠른 의사결정"],
      requiredTools: ["Figma"],
      preferred: ["B2B SaaS 경험", "HTML/CSS 이해"],
      keywords: [
        { keyword: "초기 멤버", count: 3 },
        { keyword: "SaaS", count: 3 },
        { keyword: "Figma", count: 2 },
        { keyword: "브랜딩", count: 2 },
      ],
    },
  },
  {
    id: "job-05",
    title: "UX/UI 디자이너 (헬스케어 앱)",
    companyId: "atelierblue",
    platform: "기업 홈페이지",
    location: "서울 서초구",
    career: "경력 3~5년",
    employmentType: "정규직",
    postedAt: "2026-06-25",
    deadline: "2026-07-10",
    tags: ["헬스케어", "접근성", "Figma"],
    jdSummary:
      "신뢰와 접근성을 중시하는 헬스케어 서비스의 UX/UI 디자이너를 모집합니다.",
    jdFull: [
      "아틀리에블루는 디지털 헬스케어 서비스를 운영합니다.",
      "[주요 업무]",
      "- 헬스케어 앱의 정보 구조 및 UI 설계",
      "- 접근성 가이드라인(WCAG) 준수 검토",
      "- 디자인 QA 및 크로스 플랫폼 일관성 관리",
      "[자격 요건]",
      "- UX/UI 디자인 경력 3년 이상",
      "- 접근성 가이드라인에 대한 이해",
      "- Figma 기반 협업 경험",
      "[우대 사항]",
      "- 헬스케어/의료 서비스 경험",
      "- 데이터 시각화 디자인 경험",
    ],
    originalUrl: "https://atelierblue.example.com/careers/job-05",
    aiAnalysis: {
      coreSkills: ["정보 구조 설계", "접근성 검토", "디자인 QA"],
      requiredTools: ["Figma"],
      preferred: ["헬스케어 도메인 경험", "데이터 시각화"],
      keywords: [
        { keyword: "접근성", count: 5 },
        { keyword: "헬스케어", count: 3 },
        { keyword: "Figma", count: 2 },
        { keyword: "디자인 QA", count: 2 },
      ],
    },
  },
  {
    id: "job-06",
    title: "주니어 UI 디자이너",
    companyId: "greenfield",
    platform: "원티드",
    location: "서울 강남구",
    career: "신입",
    employmentType: "정규직",
    postedAt: "2026-07-02",
    deadline: "2026-07-25",
    tags: ["신입", "Figma", "핀테크"],
    jdSummary:
      "신입 UI 디자이너를 모집합니다. 체계적인 온보딩과 멘토링 프로그램을 제공합니다.",
    jdFull: [
      "그린필드에서 커리어를 시작할 주니어 UI 디자이너를 찾습니다.",
      "[주요 업무]",
      "- 시니어 디자이너와 함께 UI 화면 설계 및 컴포넌트 제작",
      "- 디자인 시스템 문서화 보조",
      "[자격 요건]",
      "- Figma 기본 활용 가능",
      "- UX/UI 디자인 전공 또는 포트폴리오 보유",
      "[우대 사항]",
      "- 인턴 또는 프로젝트 경험",
      "- 협업 툴(Notion, Jira) 사용 경험",
    ],
    originalUrl: "https://www.wanted.co.kr/wd/job-06",
    aiAnalysis: {
      coreSkills: ["UI 화면 설계", "컴포넌트 제작", "문서화"],
      requiredTools: ["Figma"],
      preferred: ["인턴/프로젝트 경험", "Notion", "Jira"],
      keywords: [
        { keyword: "신입", count: 3 },
        { keyword: "Figma", count: 3 },
        { keyword: "온보딩", count: 2 },
        { keyword: "멘토링", count: 2 },
      ],
    },
  },
  {
    id: "job-07",
    title: "Product Designer (커머스 그로스팀)",
    companyId: "moonlit",
    platform: "LinkedIn",
    location: "서울 성동구",
    career: "경력 3~5년",
    employmentType: "정규직",
    postedAt: "2026-06-15",
    deadline: "2026-07-08",
    tags: ["그로스", "실험설계", "Figma"],
    jdSummary:
      "그로스팀에서 실험 기반 디자인을 담당할 프로덕트 디자이너를 찾습니다.",
    jdFull: [
      "문릿랩스 그로스팀에서 함께할 프로덕트 디자이너를 모집합니다.",
      "[주요 업무]",
      "- 그로스 실험 설계 및 UI 변형 제작",
      "- 데이터 분석가와 협업한 지표 기반 의사결정",
      "[자격 요건]",
      "- 3년 이상의 프로덕트 디자인 경력",
      "- 데이터 기반 의사결정 경험",
      "[우대 사항]",
      "- 그로스 해킹 관련 경험",
      "- SQL 기초 지식",
    ],
    originalUrl: "https://www.linkedin.com/jobs/view/job-07",
    aiAnalysis: {
      coreSkills: ["실험 설계", "데이터 기반 의사결정", "UI 변형 제작"],
      requiredTools: ["Figma"],
      preferred: ["그로스 해킹 경험", "SQL 기초"],
      keywords: [
        { keyword: "그로스", count: 4 },
        { keyword: "실험", count: 3 },
        { keyword: "데이터", count: 3 },
      ],
    },
  },
  {
    id: "job-08",
    title: "UX 리서처 겸 UI 디자이너",
    companyId: "atelierblue",
    platform: "잡코리아",
    location: "서울 서초구",
    career: "경력 1~3년",
    employmentType: "계약직",
    postedAt: "2026-06-29",
    deadline: "2026-07-12",
    tags: ["UX 리서치", "헬스케어", "Figma"],
    jdSummary:
      "UX 리서치와 UI 디자인을 겸할 수 있는 디자이너를 계약직으로 모집합니다.",
    jdFull: [
      "아틀리에블루 리서치팀에서 함께할 디자이너를 찾습니다.",
      "[주요 업무]",
      "- 사용자 인터뷰 및 설문 설계/진행",
      "- 리서치 결과를 반영한 UI 개선",
      "[자격 요건]",
      "- UX 리서치 경험 1년 이상",
      "- Figma 활용 가능",
      "[우대 사항]",
      "- 헬스케어 도메인 리서치 경험",
    ],
    originalUrl: "https://www.jobkorea.co.kr/Recruit/GI_Read/job-08",
    aiAnalysis: {
      coreSkills: ["사용자 인터뷰", "설문 설계", "리서치-UI 연결"],
      requiredTools: ["Figma"],
      preferred: ["헬스케어 리서치 경험"],
      keywords: [
        { keyword: "리서치", count: 5 },
        { keyword: "인터뷰", count: 3 },
        { keyword: "Figma", count: 2 },
      ],
    },
  },
];

export interface NotificationLogItem {
  id: string;
  channel: "이메일" | "푸시";
  message: string;
  sentAt: string;
}

export const notificationLog: NotificationLogItem[] = [
  {
    id: "noti-01",
    channel: "이메일",
    message: "'그린필드'에 신규 공고가 등록되었습니다: 주니어 UI 디자이너",
    sentAt: "2026-07-02",
  },
  {
    id: "noti-02",
    channel: "푸시",
    message: "관심 키워드 'Figma'가 포함된 공고 2건이 새로 등록되었습니다.",
    sentAt: "2026-07-01",
  },
  {
    id: "noti-03",
    channel: "이메일",
    message: "'아틀리에블루'의 UX 리서처 겸 UI 디자이너 공고 마감이 3일 남았습니다.",
    sentAt: "2026-06-29",
  },
  {
    id: "noti-04",
    channel: "푸시",
    message: "관심 키워드 '디자인 시스템'이 포함된 공고가 새로 등록되었습니다.",
    sentAt: "2026-06-28",
  },
];

export const crawledJobPostings: JobPosting[] = crawledJobsData as JobPosting[];

export const allJobPostings: JobPosting[] = [...jobPostings, ...crawledJobPostings];

export function getCompanyById(id: string): Company | undefined {
  return companies.find((c) => c.id === id);
}

export function getJobById(id: string): JobPosting | undefined {
  return allJobPostings.find((j) => j.id === id);
}

export function getJobsByCompany(companyId: string): JobPosting[] {
  return allJobPostings.filter((j) => j.companyId === companyId);
}
